# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GAWj3clLgoUxaoGyuzF5MLI0E0W1YufI
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -U bitsandbytes transformers peft accelerate trl datasets

!pip uninstall unsloth unsloth_zoo -y
!pip install --upgrade --force-reinstall --no-cache-dir --no-deps unsloth unsloth_zoo
!pip install --upgrade xformers trl transformers accelerate bitsandbytes

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

model_id = "meta-llama/Llama-3.2-3B-Instruct"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
)
tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token

from peft import LoraConfig, get_peft_model

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, lora_config)

from trl import SFTTrainer, SFTConfig
from datasets import load_dataset

training_args = SFTConfig(
    output_dir="/content/drive/MyDrive/llama3_no_unsloth",
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    logging_steps=1,
    max_steps=100,
    optim="paged_adamw_8bit",
    fp16=False,
    bf16=True,
    max_seq_length=1024,
)

train_dataset_path =
train_dataset = load_dataset("json", data_files=train_dataset_path, split="train")

print(train_dataset)
print(train_dataset[0])

def format_prompt(example):

    return {"text": f"### Instruction:\n{example['instruction']}\n\n### Reasoning:\n{example['reasoning']}\n\n### Output:\n{example['output']}"}

train_dataset = train_dataset.map(format_prompt)

print(train_dataset[0]['text'])

from datasets import load_dataset


dataset_path = '/content/drive/MyDrive/master_device_reasoning_dataset.jsonl'
raw_dataset = load_dataset("json", data_files=dataset_path, split="train")

def format_instruction(sample):
    return {
        "text": f"### Instruction:\n{sample['instruction']}\n\n### Reasoning:\n{sample['reasoning']}\n\n### Output:\n{sample['output']}<|end_of_text|>"
    }

dataset = raw_dataset.map(format_instruction, remove_columns=raw_dataset.column_names)
raw_dataset = load_dataset("json", data_files=dataset_path, split="train")

def format_instruction(sample):
    return {
        "text": f"### Instruction:\n{sample['instruction']}\n\n### Reasoning:\n{sample['reasoning']}\n\n### Output:\n{sample['output']}<|end_of_text|>"
    }

dataset = raw_dataset.map(format_instruction, remove_columns=raw_dataset.column_names)

from trl import SFTTrainer, SFTConfig

training_args = SFTConfig(
    output_dir="/content/drive/MyDrive/llama3_no_unsloth",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    logging_steps=1,
    max_steps=300,
    optim="paged_adamw_8bit",
    fp16=False,
    bf16=False,
    remove_unused_columns=False,
    dataset_text_field="text",
)

trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    args=training_args,
)

trainer.train()

from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
import torch


model_id = "meta-llama/Llama-3.2-3B-Instruct"
adapter_path = "/content/drive/MyDrive/llama3_no_unsloth/checkpoint-300"

from transformers import BitsAndBytesConfig
bnb_config = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.float16)

base_model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto"
)
tokenizer = AutoTokenizer.from_pretrained(model_id)

model = PeftModel.from_pretrained(base_model, adapter_path)
model.eval()

def ask_the_expert(user_query):

    prompt = f"### Instruction:\n{user_query}\n\n### Reasoning:\n"

    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=256,
            temperature=0.2,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    print(response)

user_input = "I want to buy a device for AI powered features and I am a designer and content developer and I dont need costlier one but right price for the feaatures"
ask_the_expert(user_input)

!hf upload hawkiee/Device_recommender



from huggingface_hub import HfApi

api = HfApi()

api.upload_folder(
    folder_path="/content/drive/MyDrive/llama3_no_unsloth/checkpoint-300",
    repo_id="hawkiee/Device_recommender",
    repo_type="model",
    commit_message="Initial upload of device recommendation adapters"
)

print("✅ Upload Complete! View your model at: https://huggingface.co/hawkiee/Device_recommender")